- name: Main
  hosts: all
  become: true

  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks/packages.yml

    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks/facts.yml

    - name: Include tasks
      ansible.builtin.include_tasks:
        file: tasks/secure_root.yml
