- name: Main
  hosts: all

- name: Include secure root playbook
  ansible.builtin.import_playbook: tasks/secure_root.yaml

- name: Include facts playbook
  ansible.builtin.import_playbook: tasks/facts.yaml

- name: Include packages playbook
  ansible.builtin.import_playbook: tasks/packages.yaml
