- name: Main
  hosts: all

- name: Include secure root playbook
  ansible.builtin.import_playbook: tasks/secure_root.yml

- name: Include facts playbook
  ansible.builtin.import_playbook: tasks/facts.yml

- name: Include packages playbook
  ansible.builtin.import_playbook: tasks/packages.yml
